### ISSUE TITLE
大佬，能不能教一下我怎么使用你这个权限方案，可以方便加一下你的微信嘛？

### ISSUE THREAD

**Issue by YouKnowWhatYouAre** [DwArFeng/rbac-distributed-service#1]
我的微信：18674483854
本人Java萌新，想深入了解一下RBAC权限管理方案

**Comment by DwArFeng** [comment]
您好，我已添加您的微信，我们可以邮件交流，也可以微信交流。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DwArFeng/rbac-distributed-service"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月3日(星期三) 下午5:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[DwArFeng/rbac-distributed-service] 大佬，能不能教一下我怎么使用你这个权限方案，可以方便加一下你的微信嘛？ (Issue #1)





 
我的微信：18674483854
 本人Java萌新，想深入了解一下RBAC权限管理方案
